In [10]:
import numpy as np
X = np.array([[1, 3,0,5], [0,4,1,4], [0, 1 , 3, 2], [1, 6,4,6]])
from sklearn.decomposition import NMF
model = NMF(n_components=3, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_

In [11]:
H

array([[0.05524674, 2.54545216, 0.        , 1.54511188],
       [0.        , 0.59805964, 4.50405316, 0.83444273],
       [0.26840111, 0.44355354, 0.        , 1.21615354]])

In [12]:
X

array([[1, 3, 0, 5],
       [0, 4, 1, 4],
       [0, 1, 3, 2],
       [1, 6, 4, 6]])

In [13]:
W

array([[0.58636457, 0.        , 3.3795893 ],
       [1.30330878, 0.22511111, 1.37933833],
       [0.07173708, 0.66801198, 1.03231037],
       [1.75226985, 0.88583713, 2.17190372]])

In [15]:
gen = model.inverse_transform(W)

In [17]:
rows, cols = gen.shape
for i in range(rows):
    for j in range(cols):
        gen[i][j] = round(gen[i][j])

In [18]:
gen

array([[1., 3., 0., 5.],
       [0., 4., 1., 4.],
       [0., 1., 3., 2.],
       [1., 6., 4., 6.]])